Faker es una librería de Python que sirve para generar datos falsos (dummy data) de manera sencilla. Muy útil para crear conjuntos de datos para probar aplicaciones, hacer demostraciones o entrenar modelos con datos simulados. Algunos de los datos que se pueden simular con Faker son:

+ Persona
    * fake.name() → Nombre completo
    * fake.first_name() → Nombre
    * fake.last_name() → Apellido
    * fake.prefix() → Prefijo (Sr., Dr., etc.)
    * fake.suffix() → Sufijo (Jr., PhD, etc.)
    * fake.simple_profile() → Perfil simple (nombre, sexo, etc.)
    * fake.profile() → Perfil más completo
+ Dirección
    * fake.address() → Dirección completa
    * fake.street_name() → Nombre de la calle
    * fake.street_address() → Dirección de calle
    * fake.city() → Ciudad
    * fake.state() → Estado/provincia
    * fake.country() → País
    * fake.postcode() → Código postal
    * fake.geo_coordinate() → Coordenada geográfica
+ Contacto / Internet
    * fake.email() → Correo electrónico
    * fake.safe_email() → Correo seguro (ej: ejemplo@example.com)
    * fake.user_name() → Nombre de usuario
    * fake.password() → Contraseña
    * fake.url() → URL
    * fake.domain_name() → Dominio
    * fake.ipv4() / fake.ipv6() → IPs
+ Teléfonos
    * fake.phone_number() → Número de teléfono
    * fake.msisdn() → Número de teléfono móvil
+ Fechas / Tiempo
    * fake.date() → Fecha
    * fake.date_time() → Fecha y hora
    * fake.date_of_birth() → Fecha de nacimiento
    * fake.future_date() → Fecha futura
    * fake.past_date() → Fecha pasada
+ Finanzas
    * fake.credit_card_number() → Número de tarjeta de crédito
    * fake.credit_card_provider() → Tipo de tarjeta (Visa, MasterCard, etc.)
    * fake.credit_card_expire() → Fecha de expiración
+ Texto
    * fake.word() → Una palabra
    * fake.sentence() → Una oración
    * fake.paragraph() → Un párrafo
    * fake.text() → Texto largo
+ Trabajo / Empresa
    * fake.company() → Nombre de empresa
    * fake.job() → Profesión
    * fake.catch_phrase() → Eslogan
+ Otros
    * fake.random_int() → Entero aleatorio
    * fake.random_number() → Número aleatorio
    * fake.boolean() → Verdadero/Falso
    * fake.color_name() → Nombre de color
    * fake.language_name() → Nombre de idioma
    * fake.currency_name() → Nombre de moneda
    * fake.license_plate() → Placa de vehículo

In [14]:
from faker import Faker

fake = Faker("es_MX")
Faker.seed(1234)

print(fake.name())         
print(fake.address())      
print(fake.email())        
print(fake.date_of_birth())
print(fake.date_of_birth())
print(fake.company())
print(fake.date())

Camilo Aguilar
Boulevard Mota 000 597
San Conchita de la Montaña, GRO 08731
mbarrientos@example.net
1919-12-16
1976-10-21
Proyectos Valadez, Barajas y Madrid
1996-10-07

In [ ]:
from datetime import date
# Rango fijo usando objetos date
start = date(2000, 1, 1)
end = date(2020, 12, 31)

print(fake.date_between(start_date=start, end_date=end))

2007-06-17

In [21]:
start = date(2000, 1, 1)
end = date(2000, 12, 31)
[fake.date_between(start_date=start, end_date=end) for _ in range(100)]

[datetime.date(2000, 11, 27),
 datetime.date(2000, 3, 21),
 datetime.date(2000, 7, 3),
 datetime.date(2000, 8, 26),
 datetime.date(2000, 10, 22),
 datetime.date(2000, 9, 6),
 datetime.date(2000, 4, 30),
 datetime.date(2000, 7, 24),
 datetime.date(2000, 2, 29),
 datetime.date(2000, 7, 1),
 datetime.date(2000, 12, 9),
 datetime.date(2000, 12, 12),
 datetime.date(2000, 2, 21),
 datetime.date(2000, 7, 13),
 datetime.date(2000, 8, 14),
 datetime.date(2000, 2, 23),
 datetime.date(2000, 12, 12),
 datetime.date(2000, 3, 29),
 datetime.date(2000, 2, 29),
 datetime.date(2000, 7, 3),
 datetime.date(2000, 7, 3),
 datetime.date(2000, 10, 9),
 datetime.date(2000, 11, 7),
 datetime.date(2000, 4, 29),
 datetime.date(2000, 9, 15),
 datetime.date(2000, 7, 24),
 datetime.date(2000, 7, 14),
 datetime.date(2000, 8, 6),
 datetime.date(2000, 6, 11),
 datetime.date(2000, 5, 15),
 datetime.date(2000, 12, 5),
 datetime.date(2000, 10, 5),
 datetime.date(2000, 9, 3),
 datetime.date(2000, 11, 19),
 datetime.date(2000, 8, 8),
 datetime.date(2000, 1, 26),
 datetime.date(2000, 3, 24),
 datetime.date(2000, 10, 20),
 datetime.date(2000, 5, 6),
 datetime.date(2000, 12, 8),
 datetime.date(2000, 9, 8),
 datetime.date(2000, 5, 18),
 datetime.date(2000, 6, 28),
 datetime.date(2000, 1, 20),
 datetime.date(2000, 6, 12),
 datetime.date(2000, 1, 30),
 datetime.date(2000, 4, 17),
 datetime.date(2000, 12, 5),
 datetime.date(2000, 2, 23),
 datetime.date(2000, 9, 4),
 datetime.date(2000, 8, 25),
 datetime.date(2000, 9, 9),
 datetime.date(2000, 10, 16),
 datetime.date(2000, 11, 11),
 datetime.date(2000, 5, 10),
 datetime.date(2000, 5, 15),
 datetime.date(2000, 3, 4),
 datetime.date(2000, 8, 21),
 datetime.date(2000, 3, 18),
 datetime.date(2000, 3, 12),
 datetime.date(2000, 12, 27),
 datetime.date(2000, 8, 14),
 datetime.date(2000, 9, 23),
 datetime.date(2000, 7, 2),
 datetime.date(2000, 2, 18),
 datetime.date(2000, 11, 28),
 datetime.date(2000, 8, 25),
 datetime.date(2000, 1, 19),
 datetime.date(2000, 11, 29),
 datetime.date(2000, 6, 19),
 datetime.date(2000, 8, 6),
 datetime.date(2000, 5, 15),
 datetime.date(2000, 5, 24),
 datetime.date(2000, 10, 11),
 datetime.date(2000, 3, 26),
 datetime.date(2000, 1, 4),
 datetime.date(2000, 4, 24),
 datetime.date(2000, 12, 25),
 datetime.date(2000, 2, 13),
 datetime.date(2000, 8, 6),
 datetime.date(2000, 11, 11),
 datetime.date(2000, 7, 13),
 datetime.date(2000, 8, 4),
 datetime.date(2000, 7, 15),
 datetime.date(2000, 4, 27),
 datetime.date(2000, 5, 12),
 datetime.date(2000, 12, 4),
 datetime.date(2000, 9, 16),
 datetime.date(2000, 8, 22),
 datetime.date(2000, 6, 15),
 datetime.date(2000, 11, 28),
 datetime.date(2000, 11, 16),
 datetime.date(2000, 12, 19),
 datetime.date(2000, 7, 17),
 datetime.date(2000, 5, 29),
 datetime.date(2000, 3, 10),
 datetime.date(2000, 4, 9),
 datetime.date(2000, 11, 12),
 datetime.date(2000, 3, 4),
 datetime.date(2000, 12, 11)]

In [23]:
import pandas as pd
pd.date_range("2024-01-01", periods=30, freq="D")

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10', '2024-01-11', '2024-01-12',
               '2024-01-13', '2024-01-14', '2024-01-15', '2024-01-16',
               '2024-01-17', '2024-01-18', '2024-01-19', '2024-01-20',
               '2024-01-21', '2024-01-22', '2024-01-23', '2024-01-24',
               '2024-01-25', '2024-01-26', '2024-01-27', '2024-01-28',
               '2024-01-29', '2024-01-30'],
              dtype='datetime64[ns]', freq='D')

In [26]:
import random
productos = ["Laptop", "Teléfono", "Tablet", "Mouse", "Teclado", "Auriculares", "Silla", "Escritorio", "Papelería", "Monitor"]
[random.choice(productos) for _ in range(10)]

['Escritorio',
 'Monitor',
 'Auriculares',
 'Teclado',
 'Tablet',
 'Teclado',
 'Escritorio',
 'Silla',
 'Monitor',
 'Papelería']

In [27]:
import numpy as np
np.random.randint(1, 101, size=10)

array([90,  9, 89, 82, 79, 79, 28, 96, 35, 43])

In [34]:
Faker.seed(1234)
random.seed(1234)
np.random.seed(1234) 

# Dataset ficticio de ventas
data = {
    "fecha": [fake.date_between(start_date=start, end_date=end) for _ in range(100)],
    "producto": [random.choice(productos) for _ in range(100)],
    "cantidad": np.random.randint(1, 101, size=100),
    "precio_unitario": np.random.randint(500, 10000, size=100),
    "ciudad": random.choices(["Ciudad de México", "Guadalajara", "Monterrey", "Puebla", "Tijuana"], k=100),
}

df = pd.DataFrame(data)

In [35]:
df

         fecha    producto  cantidad  precio_unitario            ciudad
0   2000-12-18  Escritorio        48             5065            Puebla
1   2000-06-09    Teléfono        84             4968         Monterrey
2   2000-01-03      Laptop        39             8294            Puebla
3   2000-11-28    Teléfono        54             7669           Tijuana
4   2000-12-08     Monitor        77             1666  Ciudad de México
..         ...         ...       ...              ...               ...
95  2000-01-26   Papelería        72             3922  Ciudad de México
96  2000-05-24  Escritorio        69             8599         Monterrey
97  2000-01-18     Teclado        82             2477       Guadalajara
98  2000-04-14     Teclado        53             5245           Tijuana
99  2000-01-14    Teléfono        65             5168           Tijuana

[100 rows x 5 columns]

In [36]:
# Calcular ingresos
df["ingreso"] = df["cantidad"] * df["precio_unitario"]

In [37]:
coords = {
    "Ciudad de México": [19.4326, -99.1332],
    "Guadalajara": [20.6597, -103.3496],
    "Monterrey": [25.6866, -100.3161],
    "Puebla": [19.0413, -98.2062],
    "Tijuana": [32.5149, -117.0382]
}

df["lat"] = df["ciudad"].map(lambda c: coords[c][0])
df["lon"] = df["ciudad"].map(lambda c: coords[c][1])

In [38]:
df

,fecha,producto,cantidad,precio_unitario,ciudad,ingreso,lat,lon
0,2000-12-18,Escritorio,48,5065,Puebla,243120,19.0413,-98.2062
1,2000-06-09,Teléfono,84,4968,Monterrey,417312,25.6866,-100.3161
2,2000-01-03,Laptop,39,8294,Puebla,323466,19.0413,-98.2062
3,2000-11-28,Teléfono,54,7669,Tijuana,414126,32.5149,-117.0382
4,2000-12-08,Monitor,77,1666,Ciudad de México,128282,19.4326,-99.1332
...,...,...,...,...,...,...,...,...
95,2000-01-26,Papelería,72,3922,Ciudad de México,282384,19.4326,-99.1332
96,2000-05-24,Escritorio,69,8599,Monterrey,593331,25.6866,-100.3161
97,2000-01-18,Teclado,82,2477,Guadalajara,203114,20.6597,-103.3496
98,2000-04-14,Teclado,53,5245,Tijuana,277985,32.5149,-117.0382
99,2000-01-14,Teléfono,65,5168,Tijuana,335920,32.5149,-117.0382

In [32]:
# Exportar a JSON para usar en el dashboard
df.to_json("ventas.json", orient="records")