In [ ]:
import pandas as pd
from sqlalchemy import create_engine

In [49]:
engine = create_engine(
    "mariadb+mariadbconnector://root@localhost:3306/IbaktorExamples"
)

In [50]:
query = "SHOW TABLES;"

In [51]:
pd.read_sql(query, engine)

OperationalError: (mariadb.OperationalError) Access denied for user 'root'@'localhost'
(Background on this error at: https://sqlalche.me/e/14/e3q8)

In [52]:
engine = create_engine(
    "mariadb+mariadbconnector://python_user@localhost:3306/IbaktorExamples"
)

In [53]:
query = "SHOW TABLES;"

In [54]:
pd.read_sql(query, engine)

  Tables_in_IbaktorExamples
0                    ventas

In [55]:
query = """
WITH metricas_mensuales AS (
    SELECT *
    FROM ventas
    )
SELECT  *
    FROM metricas_mensuales
ORDER BY mes;
"""

In [56]:
pd.read_sql(query, engine)

OperationalError: (mariadb.OperationalError) Table 'IbaktorExamples.ventas' doesn't exist in engine
[SQL:
WITH metricas_mensuales AS (
    SELECT *
    FROM ventas
    )
SELECT  *
    FROM metricas_mensuales
ORDER BY mes;
]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

In [74]:
query = """
SELECT 
    mes,
    ventas_totales,
    num_productos,
    ventas_totales / num_productos as venta_promedio_por_producto
FROM (
    SELECT 
        DATE_FORMAT(fecha, 'Año: %Y, mes: %M') as mes,
        SUM(cantidad * precio) as ventas_totales,
        COUNT(DISTINCT producto) as num_productos
    FROM ventas
    GROUP BY DATE_FORMAT(fecha, 'Año: %Y, mes: %M')
) AS metricas_mensuales
ORDER BY mes;
"""

In [75]:
pd.read_sql(query, engine)

,mes,ventas_totales,num_productos,venta_promedio_por_producto
0,"Año: 2024, mes: January",8249.82,2,4124.91

In [61]:
df_aux = pd.read_sql(query, engine)

In [62]:
import plotly.express as px
fig = px.line(df_aux, x='mes', y='ventas_totales', 
              title='Tendencia de Ventas Mensuales')
fig.show()

In [60]:
df

       mes  ventas_totales  num_productos  venta_promedio_por_producto
0  2025-01           700.0              2                        350.0
1  2025-02           740.0              2                        370.0
2  2025-03           744.0              2                        372.0

In [ ]:
# Visualización con plotly (más interactiva)
fig = px.line(df, x='mes', y='ventas_totales', 
              title='Tendencia de Ventas Mensuales')
fig.show()

Otra forma de conectarse:

In [ ]:
import mariadb

# Conecta a la base de datos
try:
    conn = mariadb.connect(
        user="python_user",
        password="",
        host="localhost",
        port=3306,
        database="IbaktorExamples"
    )
    print("Conexión exitosa a MariaDB")

except mariadb.Error as e:
    print(f"Error al conectar a MariaDB: {e}")
    exit(1)

Conexión exitosa a MariaDB

In [64]:
# Crear cursor
cur = conn.cursor()

In [65]:
# Ejecutar una consulta
cur.execute("SELECT NOW();")

In [66]:
cur

In [67]:
# Obtener resultados
for (now,) in cur:
    print("Fecha y hora del servidor:", now)

# Cerrar conexión
conn.close()

Fecha y hora del servidor: 2025-07-12 11:21:51